FROM node:20 as builder
WORKDIR /usr/src/app
COPY packages/client/package*.json /usr/src/app/
RUN npm ci
COPY packages/common /usr/src/common
COPY packages/client/ /usr/src/app/
RUN npm run build

FROM nginx:latest as prod
COPY packages/client/nginx.conf /etc/nginx/conf.d/default.conf
COPY packages/common /usr/src/common
COPY --from=builder /usr/src/app/dist/client /usr/share/nginx/html
EXPOSE 80