export const ASSOCIATIONS = [
    'CEGM',
    'CEGMines',
    'CEGP',
    'CEAP',
    'CEGA',
    'CEGBiomed',
    'CEGCh',
    'CEGCi',
    'CEGE',
    'CEGéo',
    'CEGI',
    'CEGInfo',
    'CEGL',
    'Agenda',
    'Allo-Poly',
    'Association des étudiants musulmans (AEMUDM)',
    'Bannière de Polytechnique',
    'CCGP - Comité de consultation en gestion de Polytechnique',
    'CCIP - Comité des Compétitions d\'Ingénierie de Polytechnique',
    'Chapitre étudiant de l\'OSA-SPIE',
    'CLÉE - Comité de Liaison Étudiants/Entreprises de Polytechnique',
    'Club Poly Énergies',
    'Comic',
    'Comité à l\'éducation pour l\'année préparatoire',
    'Comité international de projets outre-mer (CIPO)',
    'Foire aux livres',
    'Houblonneries',
    'Ingénieurs sans frontières (ISF)',
    'Jeux de Génie - EPM',
    'Le Polyscope',
    'Le Pub',
    'PINEP',
    'Poly-Débat',
    'Poly-FI',
    'Poly-Habs',
    'Poly-international',
    'Poly-Monde',
    'Poly-Out',
    'Poly-Party',
    'Poly-Projet',
    'Poly-Show',
    'Poly-Théâtre',
    'PolyAir',
    'PolyExplore',
    'PolyFinances',
    'PolyJam',
    'PolyParcs',
    'Polyphonie',
    'PolyPhoto',
    'PolyRad',
    'PolySphère',
    'PolySports',
    'PolyTV',
    'PolyVoile',
    'Poly Entrepreneuriat',
    'Poly Hx',
    'Projet PC2',
    'Promo 146',
    'Station Polytechnique',
    'STEP',
]