export const INTERESTS = [
    "Animation stop-motion",
    "Antiquités",
    "Apiculture",
    "Archéologie",
    "Astronomie",
    "Bandes dessinées",
    "Barbecue",
    "Basketball",
    "Bibliophilie",
    "Billard",
    "Bingo",
    "Botanique",
    "Bougie artisanale",
    "Bricolage",
    "Bridge",
    "Broderie",
    "Calligraphie",
    "Camping",
    "Canoë-kayak",
    "Chasse au trésor",
    "Chasse photographique",
    "Chorale communautaire",
    "Cinéma d'animation",
    "Cinéma",
    "Collection de pièces de monnaie",
    "Collection de timbres",
    "Comédies musicales",
    "Confitures maison",
    "Course à pied",
    "Course de chevaux",
    "Couture",
    "Création de bijoux",
    "Création de mosaïques",
    "Critique de films",
    "Crochet",
    "Cuisine végétalienne",
    "Cuisine",
    "Curling",
    "Danse contemporaine",
    "Danse",
    "Découpage",
    "Dégustation de thé",
    "Dégustation de vins",
    "Dessin",
    "Disney",
    "Doctor Who",
    "Documentaires",
    "Échecs",
    "Écriture",
    "Élevage d'animaux de compagnie",
    "Élevage de plantes d'intérieur",
    "Énigmes et casse-tête",
    "Escalade",
    "Escape games",
    "Escrime",
    "Étude de la généalogie",
    "Étude de la météorologie",
    "Étude des constellations",
    "Étude des étoiles",
    "Étude des insectes",
    "Étude des oiseaux",
    "Étude des sciences naturelles",
    "Fabrication de bijoux",
    "Fabrication de chandelles",
    "Fléchettes",
    "Football",
    "Game of Thrones",
    "Géologie",
    "Golf",
    "Graffiti",
    "Guitare",
    "Gymnastique",
    "Harry Potter",
    "Hip-hop",
    "Histoire de l'art",
    "Jardinage",
    "Jazz",
    "Jeu de cartes",
    "Jeu de dames",
    "Jeu de dominos",
    "Jeu de tarot",
    "Jeux de société",
    "Jeux vidéo",
    "Jogging",
    "Karaoké",
    "Lancer de frisbee",
    "Le Seigneur des Anneaux",
    "Lecture de poésie",
    "Lecture de roman classique",
    "Lecture",
    "Livres audio",
    "Manga",
    "Marionnettes",
    "Marvel Cinematic Universe",
    "Mixologie",
    "Modélisme",
    "Mosaïque",
    "Musique classique",
    "Musique électronique",
    "Musique",
    "Natation",
    "Observation des étoiles",
    "Observation des papillons",
    "Origami",
    "Patin à roulettes",
    "Patinage artistique",
    "Patinage de vitesse",
    "Pâtisserie",
    "Pêche",
    "Peinture",
    "Percussions",
    "Pétanque",
    "Photographie",
    "Piano",
    "Plongée",
    "Poésie",
    "Pokémon",
    "Poker",
    "Polo à cheval",
    "Poterie",
    "Randonnée",
    "Réalisation de vidéos familiales",
    "Reconstitution historique",
    "Rédaction de lettres manuscrites",
    "Reliure de livres",
    "Réparation de vélos",
    "Restauration de meubles anciens",
    "Rock'n'roll",
    "Romans policiers",
    "Science-fiction",
    "Scrapbooking",
    "Sculpture",
    "Séries télévisées",
    "Ski",
    "Star Trek",
    "Star Wars",
    "Sudoku",
    "Taylor Swift",
    "Tennis",
    "The Hunger Games",
    "Théâtre",
    "Tissage",
    "Tricot",
    "Ultimate Frisbee",
    "Vélo",
    "Violon",
    "Visite de jardins botaniques",
    "Visite de musées d'art",
    "Visite de parcs nationaux",
    "Vol en montgolfière",
    "Voyage",
    "Water-polo",
]