export const QUESTIONS = [
    "Qu'est-ce que tu penses que je fais pour m'amuser ?",
    'Comment as-tu choisi ton programme ?',
    "Si tu n'étais pas à l'école, que ferais-tu ?",
    'À quelle distance de chez toi es-tu ?',
    "Comment se passe l'école en un mot ?",
    "Que penses-tu que faire après l'école ?",
    "Qu'est-ce que je devrais regarder dès que j'aurai du temps ?",
    "Quelle caractéristique principale penses-tu que j'ai ?",
    'Quelle est la chose la plus inexplicable qui te soit arrivée ?',
    'Quelle est ta caractéristique la plus toxique que tu peux admettre ?',
    'À quoi penses-tu trop en ce moment ?',
    "Qu'est-ce que toi plus jeune aurait du mal à croire de ta vie aujourd'hui ?",
    'Quel est ton adjectif préféré pour te décrire et pourquoi ?',
    'Quelle est la plus grosse erreur que tu aies commise ?',
    'Si nous étions un groupe de musique, quel serait notre nom ?',
    'Quel souvenir te fait instantanément sourire ?',
    'À quoi penses-tu le plus souvent ?',
    'Quel est quelque chose que tu apprécies et dont tu ne te lasses jamais ?',
    "Quelle est une chose qui devrait être enseignée, mais ne l'est pas ?",
    "Si tu avais une étiquette d'avertissement, que dirait-elle ?",
    'Un étranger a-t-il déjà changé ta vie ?',
    'Quel est le compliment que tu préfères recevoir ?',
    'Quel est ton tout premier souvenir de bonheur ?',
    "Si tu devais résumer l'espèce humaine en 3 mots, quels seraient ces mots ?",
    "Si tu mourais aujourd'hui, quels regrets aurais-tu de ta vie ?",
    'Pour quoi es-tu le plus reconnaissant en ce moment ?',
    'Quel conseil en matière de rencontres donnerais-tu à ton moi plus jeune ?',
    'Quelle est la dernière chose que tu as mentie ?',
    "Quand as-tu ressenti pour la dernière fois de la chance d'être toi ?",
    "Quelle est la pire hypothèse que quelqu'un ait faite à ton sujet ?",
    "Qu'as-tu le plus peur : de l'échec ou du succès, et pourquoi ?",
    "Quelle est la caractéristique de personnalité que tu détestes le plus chez quelqu'un ?",
    'Quelle est ta citation de chanson préférée à laquelle tu peux penser spontanément ?',
];
