name: API

on:
  push:
    paths:
      - packages/api/**
      - packages/common/**
      - Dockerfile.api
      - .github/workflows/api.yml
    tags:
      - v*
  pull_request:
    paths:
      - packages/api/**
      - packages/common/**
      - Dockerfile.api
      - .github/workflows/api.yml
  workflow_dispatch:

defaults:
  run:
    shell: bash

env:
  SERVICE: api
  REGION: europe-west1
  PROJECT: projet-agir-2024
  ENVIRONMENT: prod

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: packages/${{env.SERVICE}}/package-lock.json
      - name: Install dependencies
        run: |
          cd packages/$SERVICE
          npm ci
      - name: Lint
        run: |
          cd packages/$SERVICE
          npm run lint
      - name: JSCPD
        run: |
          cd packages/$SERVICE
          npm run jscpd

  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: 20
  #         cache: 'npm'
  #         cache-dependency-path: packages/${{env.SERVICE}}/package-lock.json
  #     - name: Install dependencies
  #       run: |
  #         cd packages/$SERVICE
  #         npm ci
  #     - name: Test
  #       run: make test-api

  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - run: cd packages/$SERVICE
      - name: Build
        run: |
          docker buildx build \
            -f Dockerfile.api \
            --platform linux/amd64 \
            --target prod \
            -t $REGION-docker.pkg.dev/$PROJECT/$PROJECT-$ENVIRONMENT/$SERVICE \
            .
      - id: 'auth'
        if: startsWith(github.event.ref, 'refs/tags/')
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Configure Docker
        if: startsWith(github.event.ref, 'refs/tags/')
        run: gcloud auth configure-docker $REGION-docker.pkg.dev
      - name: Push
        if: startsWith(github.event.ref, 'refs/tags/')
        run: docker push $REGION-docker.pkg.dev/$PROJECT/$PROJECT-$ENVIRONMENT/$SERVICE

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    if: startsWith(github.event.ref, 'refs/tags/')
    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - run: |
          gcloud run deploy $PROJECT-$ENVIRONMENT-$SERVICE \
            --image=$REGION-docker.pkg.dev/$PROJECT/$PROJECT-$ENVIRONMENT/$SERVICE \
            --region=$REGION \
            --project=$PROJECT
      - run: |
          gcloud run services update-traffic $PROJECT-$ENVIRONMENT-$SERVICE \
            --region=$REGION \
            --project=$PROJECT \
            --to-latest